export enum VehicleErrorCode {
  VEHICLE_NOT_FOUND         = "VEHICLE_NOT_FOUND",
  VEHICLE_ALREADY_DELETED   = "VEHICLE_ALREADY_DELETED",
  VEHICLE_CURRENTLY_BOOKED  = "VEHICLE_CURRENTLY_BOOKED",
  RC_NUMBER_ALREADY_EXISTS  = "VEHICLE_RC_NUMBER_EXISTS",
  OWNER_PROFILE_NOT_FOUND   = "VEHICLE_OWNER_PROFILE_NOT_FOUND",
  UNAUTHORIZED              = "VEHICLE_UNAUTHORIZED",
}